{
 "title": "Azure Web App Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "subscription", "label": "Subscription ID", "query": "${subscription_id}" },
   { "name": "resource_group", "label": "Resource Group", "query": "${resource_group}" },
   {
    "name": "WebApp",
    "label": "Web App",
    "query": "ResourceNames($subscription, $resource_group, Microsoft.Web/sites)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Time - $WebApp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "repeat": "WebApp",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "subscription": "$subscription",
     "azureMonitor": {
      "resourceGroup": "$resource_group",
      "metricDefinition": "Microsoft.Web/sites",
      "metricNamespace": "Microsoft.Web/sites",
      "metricName": "CpuTime",
      "aggregation": "Average",
      "timeGrain": "auto",
      "resourceName": "$WebApp"
     }
    }
   ]
  },
  {
   "title": "Memory Working Set - $WebApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "repeat": "WebApp",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "subscription": "$subscription",
     "azureMonitor": {
      "resourceGroup": "$resource_group",
      "metricDefinition": "Microsoft.Web/sites",
      "metricNamespace": "Microsoft.Web/sites",
      "metricName": "MemoryWorkingSet",
      "aggregation": "Average",
      "timeGrain": "auto",
      "resourceName": "$WebApp"
     }
    }
   ]
  },
  {
   "title": "Sum of Requests - $WebApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "repeat": "WebApp",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "subscription": "$subscription",
     "azureMonitor": {
      "resourceGroup": "$resource_group",
      "metricDefinition": "Microsoft.Web/sites",
      "metricNamespace": "Microsoft.Web/sites",
      "metricName": "Requests",
      "aggregation": "Average",
      "timeGrain": "auto",
      "resourceName": "$WebApp"
     }
    }
   ]
  },
  {
   "title": "HTTP Server Errors - $WebApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "repeat": "WebApp",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "subscription": "$subscription",
     "azureMonitor": {
      "resourceGroup": "$resource_group",
      "metricDefinition": "Microsoft.Web/sites",
      "metricNamespace": "Microsoft.Web/sites",
      "metricName": "Http5xx",
      "aggregation": "Average",
      "timeGrain": "auto",
      "resourceName": "$WebApp"
     }
    }
   ]
  },
  {
   "title": "Avg Response Time - $WebApp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "repeat": "WebApp",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "subscription": "$subscription",
     "azureMonitor": {
      "resourceGroup": "$resource_group",
      "metricDefinition": "Microsoft.Web/sites",
      "metricNamespace": "Microsoft.Web/sites",
      "metricName": "AverageResponseTime",
      "aggregation": "Average",
      "timeGrain": "auto",
      "resourceName": "$WebApp"
     }
    }
   ]
  }
 ]
}